services:

  # FastAPI HTTP API service
  api:
    build: ./server
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] # Run FastAPI with Uvicorn in development mode
    volumes:
      - ./server/app:/code/app
      - ./server/storage:/code/storage
    ports:
      - "8000:8000" # host:container
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # Database connection string
      REDIS_URL: ${REDIS_URL} # Redis connection URL
    depends_on:
      - db
      - redis

  # Celery worker service
  worker:
    build: ./server
    command: celery -A app.celery_app.celery_app worker --loglevel=info # -A points to the Celery app instance
    volumes:
      - ./server/app:/code/app # Mount source code for live development and task changes
      - ./server/storage:/code/storage
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL} # Redis connection URL
    depends_on: # Worker must start after Redis (broker) and Postgres (storage)
      - redis
      - db

  # PostgreSQL database service
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: # Persist database data outside the container
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis message broker
  redis:
    image: redis:8
    ports:
      - "6379:6379"
      
volumes: # Named volume used by Postgres to persist data
  pgdata: