services:

  # FastAPI HTTP API service
  api:
    build: ./server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] # Run FastAPI with Uvicorn in development mode
    volumes:
      - ./server/app:/code/app
      - ./server/storage:/code/storage
    ports:
      - "127.0.0.1:8000:8000" # host:container
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # Database connection string
      REDIS_JOBS_URL: ${REDIS_JOBS_URL} # Redis jobs connection URL
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
      GOOGLE_BOOKS_MAX_RESULTS: ${GOOGLE_BOOKS_MAX_RESULTS}
      BOOK_CACHE_THRESHOLD: ${BOOK_CACHE_THRESHOLD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME_MINUTES: ${JWT_EXPIRATION_TIME_MINUTES}
      HASH_ALGORITHM : ${HASH_ALGORITHM}
      JWT_EXPIRATION_TIME_REFRESH: ${JWT_EXPIRATION_TIME_REFRESH}
      CORS_ALLOWED_ORIGINS : ${CORS_ALLOWED_ORIGINS}
      REDIS_RATELIMIT_URL : ${REDIS_RATELIMIT_URL}
      API_LOGGER_NAME : ${API_LOGGER_NAME}
      STORAGE_BACKEND : ${STORAGE_BACKEND}
      MAX_IMAGE_SIZE : ${MAX_IMAGE_SIZE}
    depends_on:
      - db
      - redis

  # Celery worker service
  worker:
    build: ./server
    command: celery -A app.celery_app.celery_app worker --loglevel=info # -A points to the Celery app instance
    volumes:
      - ./server/app:/code/app # Mount source code for live development and task changes
      - ./server/storage:/code/storage
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_JOBS_URL: ${REDIS_JOBS_URL} # Redis connection URL
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
      GOOGLE_BOOKS_MAX_RESULTS: ${GOOGLE_BOOKS_MAX_RESULTS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BOOK_CACHE_THRESHOLD: ${BOOK_CACHE_THRESHOLD}
      API_LOGGER_NAME : ${API_LOGGER_NAME}
      STORAGE_BACKEND : ${STORAGE_BACKEND}
    depends_on: # Worker must start after Redis (broker) and Postgres (storage)
      - redis
      - db

  # PostgreSQL database service
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - pgdata:/var/lib/postgresql/data # Persist database data outside the container
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql # add vector extension
    ports:
      - "127.0.0.1:5432:5432"

  # Redis message broker
  redis:
    image: redis:8
    ports:
      - "127.0.0.1:6379:6379"
      
  frontend:
    build: ./client
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

volumes: # Named volume used by Postgres to persist data
  pgdata: