import os
from dotenv import load_dotenv

load_dotenv()

# OCR api
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Google api settings
GOOGLE_BOOKS_API_KEY = os.getenv("GOOGLE_BOOKS_API_KEY")
MAX_RESULTS = os.getenv("GOOGLE_BOOKS_MAX_RESULTS")

# Settings : 
BOOK_CACHE_THRESHOLD = float(os.getenv("BOOK_CACHE_THRESHOLD"))

# JWT and Authentication
JWT_SECRET = os.getenv("JWT_SECRET")
HASHING_ALGO = os.getenv("HASHING_ALGORITHM")

TOKEN_EXPIRE_MINUTES = os.getenv("JWT_EXPIRATION_TIME_MINUTES")
if TOKEN_EXPIRE_MINUTES is not None:
    TOKEN_EXPIRE_MINUTES : float = float(TOKEN_EXPIRE_MINUTES)

JWT_EXPIRATION_TIME_REFRESH = os.getenv("JWT_EXPIRATION_TIME_REFRESH")
if JWT_EXPIRATION_TIME_REFRESH is not None:
    JWT_EXPIRATION_TIME_REFRESH : float = float(JWT_EXPIRATION_TIME_REFRESH)